<$schema>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</$schema>
<name>SFZ</name>
<patterns>
  <include>#comment</include>
</patterns>
<patterns>
  <include>#headers</include>
</patterns>
<patterns>
  <include>#sfz1_sound-source</include>
</patterns>
<patterns>
  <include>#sfz1_instrument-settings</include>
</patterns>
<patterns>
  <include>#sfz1_region-logic</include>
</patterns>
<patterns>
  <include>#sfz1_performance-parameters</include>
</patterns>
<patterns>
  <include>#sfz1_modulation</include>
</patterns>
<patterns>
  <include>#sfz1_effects</include>
</patterns>
<patterns>
  <include>#sfz2_directives</include>
</patterns>
<patterns>
  <include>#sfz2_sound-source</include>
</patterns>
<patterns>
  <include>#sfz2_instrument-settings</include>
</patterns>
<patterns>
  <include>#sfz2_region-logic</include>
</patterns>
<patterns>
  <include>#sfz2_performance-parameters</include>
</patterns>
<patterns>
  <include>#sfz2_modulation</include>
</patterns>
<patterns>
  <include>#sfz2_curves</include>
</patterns>
<patterns>
  <include>#aria_instrument-settings</include>
</patterns>
<patterns>
  <include>#aria_region-logic</include>
</patterns>
<patterns>
  <include>#aria_performance-parameters</include>
</patterns>
<patterns>
  <include>#aria_modulation</include>
</patterns>
<patterns>
  <include>#aria_curves</include>
</patterns>
<patterns>
  <include>#aria_effects</include>
</patterns>
<repository>
  <comment>
    <patterns>
      <name>comment.block.sfz</name>
      <begin>/\*</begin>
      <beginCaptures>
        <0>
          <name>punctuation.definition.comment.sfz</name>
        </0>
      </beginCaptures>
      <end>\*/</end>
      <endCaptures>
        <0>
          <name>punctuation.definition.comment.sfz</name>
        </0>
      </endCaptures>
    </patterns>
    <patterns>
      <name>comment.line.double-slash.sfz</name>
      <begin>([\s]+)?((//)(?:\s*(?=\s|$))?)</begin>
      <beginCaptures>
        <1>
          <name>punctuation.whitespace.comment.leading.sfz</name>
        </1>
        <2>
          <name>comment.line.double-slash.sfz</name>
        </2>
        <3>
          <name>punctuation.definition.comment.sfz</name>
        </3>
      </beginCaptures>
      <end>(?=$)</end>
    </patterns>
  </comment>
  <headers>
    <patterns>
      <comment>Headers</comment>
      <name>meta.structure.header.$2.start.sfz</name>
      <match>(&lt;)(control|curve|effect|global|group|master|midi|region)(&gt;)</match>
      <captures>
        <1>
          <name>punctuation.definition.tag.begin.sfz</name>
        </1>
        <2>
          <name>keyword.control.$2.sfz</name>
        </2>
        <3>
          <name>punctuation.definition.tag.begin.sfz</name>
        </3>
      </captures>
    </patterns>
    <patterns>
      <comment>Non-compliant headers</comment>
      <name>invalid.sfz</name>
      <match>&lt;.*(?!(control|curve|effect|global|group|master|midi|region))&gt;</match>
    </patterns>
  </headers>
  <sfz1_sound-source>
    <patterns>
      <comment>opcodes: (count): (0 to 4294967296 loops)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(count)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (delay|delay_random|delay_onccN): (0 to 100 percent)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(delay(?:_random|_oncc(?:\d{1,3}))?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (end): (-1 to 4294967296 sample units)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(end)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive_or_neg1</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loop_start|loop_end): (0 to 4294967296 sample units)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(loop_start|loop_end)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loop_mode): (no_loop|one_shot|loop_continuous|loop_sustain)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(loop_mode)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_loop_mode</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (offset|offset_random|offset_onccN): (0 to 4294967296 sample units)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(offset(?:_random|_oncc(?:\d{1,3}))?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sample): (any string)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sample)(=?)</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
        <2>
          <name>keyword.operator.assignment.sfz</name>
        </2>
      </beginCaptures>
      <end>(?=(\s//|$))</end>
      <contentName>string.unquoted.sfz</contentName>
    </patterns>
    <patterns>
      <comment>opcodes: (sync_beats|sync_offset): (0 to 32 beats)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sync_beats|sync_offset)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-32</include>
      </patterns>
    </patterns>
  </sfz1_sound-source>
  <sfz1_instrument-settings>
    <patterns>
      <comment>opcodes: (group|polyphony_group|off_by): (0 to 4294967296 sample units)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(group|polyphony_group|off_by)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (off_mode): (fast|normal)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(off_mode)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_fast-normal-time</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (output): (0 to 1024 MIDI Nodes)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(output)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-1024</include>
      </patterns>
    </patterns>
  </sfz1_instrument-settings>
  <sfz1_region-logic>
    <patterns>
      <comment>opcodes: (key|lokey|hikey): (0 to 127 MIDI Note or C-1 to G#9 Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(key|lokey|hikey)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.key-mapping.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (love|hivel): (0 to 127 MIDI Velocity)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lovel|hivel)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.key-mapping.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lochan|hichan): (1 to 16 MIDI Channel)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lochan|hichan)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_1-16</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loccN|hiccN): (0 to 127 MIDI Controller)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((?:lo|hi)cc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lobend|hibend): (-8192 to 8192 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lobend|hibend)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg8192-8192</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sw_lokey|sw_hikey|sw_last|sw_down|sw_up|sw_previous): (0 to 127 MIDI Note or C-1 to G#9 Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sw_(?:lokey|hikey|last|down|up|previous))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sw_vel): (current|previous)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sw_vel)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_current-previous</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lobpm|hibpm): (0 to 500 BPM)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lobpm|hibpm)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.internal-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-500</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lochanaft|hichanaft|lopolyaft|hipolyaft): (0 to 127 MIDI Controller)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lochanaft|hichanaft|lopolyaft|hipolyaft)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.internal-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lorand|hirand): (0 to 1 float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lorand|hirand)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.internal-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-1</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (seq_length|seq_position): (1 to 100 beats)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(seq_length|seq_position)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.internal-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_1-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (trigger): (attack|release|first|legato)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(trigger)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.triggers.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_attack-release-first-legato</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (on_loccN|on_hiccN): (-1 to 127 MIDI Controller)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(on_(?:lo|hi)cc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.triggers.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg1-127</include>
      </patterns>
    </patterns>
  </sfz1_region-logic>
  <sfz1_performance-parameters>
    <patterns>
      <comment>opcodes: (pan|position|width|amp_veltrack): (-100 to 100 percent)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pan|position|width|amp_veltrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg100-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (volume): (-144 to 6 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(volume)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg144-6</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amp_keycenter): (0 to 127 MIDI Note or C-1 to G#9 Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amp_keycenter)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amp_keytrack): (-96 to 12 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amp_keytrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg96-12</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amp_velcurve_N): (0 to 1 curve)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amp_velcurve_(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-1</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amp_random): (0 to 24 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amp_random)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-24</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (gain_onccN): (-144 to 48 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(gain_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg144-48</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (rt_decay): (0 to 200 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(rt_decay)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (xf_cccurve|xf_keycurve|xf_velcurve): (gain|power)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(xf_cccurve|xf_keycurve|xf_velcurve)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_gain-power</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (xfin_loccN|xfin_hiccN|xfout_loccN|xfout_hiccN|xfin_lokey|xfin_hikey|xfout_lokey|xfout_hikey|xfin_lovel|xfin_hivel|xfout_lovel|xfout_hivel): (0 to 127 MIDI Velocity)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(xfin_locc(?:\d{1,3})?|xfin_hicc(?:\d{1,3})?|xfout_locc(?:\d{1,3})?|xfout_hicc(?:\d{1,3})?|xfin_lokey|xfin_hikey|xfout_lokey|xfout_hikey|xfin_lovel|xfin_hivel|xfout_lovel|xfout_hivel)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (xfin_lokey|xfin_hikey|xfout_lokey|xfout_hikey): (0 to 127 MIDI Note or C-1 to G#9 Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(xfin_lokey|xfin_hikey|xfout_lokey|xfout_hikey)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (bend_up|bend_down|pitch_veltrack): (-9600 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(bend_up|bend_down|pitch_veltrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg9600-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (bend_step): (1 to 1200 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(bend_step)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_1-1200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pitch_keycenter): (0 to 127 MIDI Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pitch_keycenter)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pitch_keytrack): (-1200 to 1200 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pitch_keytrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg1200-1200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pitch_random): (0 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pitch_random)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (transpose): (-127 to 127 MIDI Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(transpose)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg127-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (tune): (-2400 to 2400 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(tune)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg9600-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (cutoff): (0 to arbitrary Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(cutoff)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (cutoff_onccN|cutoff_chanaft|cutoff_polyaft): (-9600 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(cutoff_oncc(?:\d{1,3})?|cutoff_chanaft|cutoff_polyaft)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg9600-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil_keytrack): (0 to 1200 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil_keytrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-1200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil_keycenter): (0 to 127 MIDI Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil_keycenter)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127_or_string_note</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil_random): (0 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil_random)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil_type): (lpf_1p|hpf_1p|lpf_2p|hpf_2p|bpf_2p|brf_2p)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil_type)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_lpf-hpf-bpf-brf</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil_veltrack): (-9600 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil_veltrack)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg9600-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (resonance): (0 to 40 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(resonance)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-40</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (eq1_freq|eq2_freq|eq3_freq): (0 to 30000 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eq1_freq|eq2_freq|eq3_freq)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.eq.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-30000</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (eq1_freq_onccN|eq2_freq_onccN|eq3_freq_onccN|eq1_vel2freq|eq2_vel2freq|eq3_vel2freq): (-30000 to 30000 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eq[1-3]_freq_oncc(?:\d{1,3})?|eq1_vel2freq|eq2_vel2freq|eq3_vel2freq)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.eq.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg30000-30000</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (eq1_bw|eq2_bw|eq3_bw): (0.0001 to 4 octaves)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eq1_bw|eq2_bw|eq3_bw)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.eq.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-4</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (eq1_bw_onccN|eq2_bw_onccN|eq3_bw_onccN|eq1_vel2bw|eq2_vel2bw|eq3_vel2bw): (-30000 to 30000 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eq[1-3]_bw_oncc(?:\d{1,3})?|eq1_vel2bw|eq2_vel2bw|eq3_vel2bw)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.eq.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg4-4</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (eq1_gain|eq2_gain|eq3_gain|eq1_gain_onccN|eq2_gain_onccN|eq3_gain_onccN|eq1_vel2gain|eq2_vel2gain|eq3_vel2gain): (-96 to 24 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eq[1-3]_(vel2)?gain|eq[1-3]_gain_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.eq.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg96-24</include>
      </patterns>
    </patterns>
  </sfz1_performance-parameters>
  <sfz1_modulation>
    <patterns>
      <comment>opcodes: (ampeg_delay_onccN|ampeg_attack_onccN|ampeg_hold_onccN|ampeg_decay_onccN|ampeg_release_onccN|ampeg_vel2delay|ampeg_vel2attack|ampeg_vel2hold|ampeg_vel2decay|ampeg_vel2release|pitcheg_vel2delay|pitcheg_vel2attack|pitcheg_vel2hold|pitcheg_vel2decay|pitcheg_vel2release|fileg_vel2delay|fileg_vel2attack|fileg_vel2hold|fileg_vel2decay|fileg_vel2release): (0 to 100 seconds)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((ampeg|fileg|pitcheg)_(((attack|decay|delay|hold|release|start|sustain)(_oncc(?:\d{1,3})?)?)|vel2(attack|decay|delay|hold|release|start|sustain)))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pitcheg_depth|fileg_depth|pitcheg_vel2depth|fileg_vel2depth): (-12000 to 12000 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pitcheg_depth|fileg_depth|pitcheg_vel2depth|fileg_vel2depth)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg12000-12000</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplfo_depth|amplfo_depthccN|amplfo_depthchanaft|amplfo_depthpolyaft): (-20 to 20 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amplfo_((depth(cc(?:\d{1,3})?)?)|depth(chan|poly)aft))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg20-20</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pitchlfo_depth|pitchlfo_depthccN|pitchlfo_depthchanaft|pitchlfo_depthpolyaft|fillfo_depth|fillfo_depthccN|fillfo_depthchanaft|fillfo_depthpolyaft): (-1200 to 1200 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((fillfo|pitchlfo)_((depth((_on)?cc(?:\d{1,3})?)?)|depth(chan|poly)aft))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg1200-1200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplfo_freqccN|amplfo_freqchanaft|amplfo_freqpolyaft|pitchlfo_freqccN|pitchlfo_freqchanaft|pitchlfo_freqpolyaft|fillfo_freqccN|fillfo_freqchanaft|fillfo_freqpolyaft): (-200 to 200 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((amplfo|fillfo|pitchlfo)_(freq|(cc(?:\d{1,3})?)?)|freq(chan|poly)aft)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg200-200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplfo_delay|amplfo_fade|pitchlfo_delay|pitchlfo_fade|fillfo_delay|fillfo_fade): (0 to 100 seconds)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((amplfo|fillfo|pitchlfo)_(delay|fade))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplfo_freq|pitchlfo_freq|fillfo_freq): (0 to 20 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amplfo_freq|pitchlfo_freq|fillfo_freq)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-20</include>
      </patterns>
    </patterns>
  </sfz1_modulation>
  <sfz1_effects>
    <patterns>
      <comment>opcodes: (effect1|effect2): (0 to 100 percent)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(effect1|effect2)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.effects.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
  </sfz1_effects>
  <sfz2_directives>
    <patterns>
      <comment>#define statement</comment>
      <match>((\#define)\s+((\$)[^\s]+)\s+(.+))\b</match>
      <captures>
        <1>
          <name>meta.generic.define.sfz</name>
        </1>
        <2>
          <name>meta.preprocessor.define.sfz</name>
        </2>
        <3>
          <name>meta.preprocessor.string.sfz</name>
        </3>
        <4>
          <name>punctuation.definition.variable.sfz</name>
        </4>
        <5>
          <name>meta.preprocessor.string.sfz</name>
        </5>
      </captures>
    </patterns>
    <patterns>
      <comment>#include statement</comment>
      <match>((\#include)\s+((").+(?=\.sfz)\.sfzh?(")))</match>
      <captures>
        <1>
          <name>meta.generic.include.sfz</name>
        </1>
        <2>
          <name>meta.preprocessor.import.sfz</name>
        </2>
        <3>
          <name>meta.preprocessor.string.sfz</name>
        </3>
        <4>
          <name>punctuation.definition.string.begin.sfz</name>
        </4>
        <5>
          <name>punctuation.definition.string.end.sfz</name>
        </5>
      </captures>
    </patterns>
    <patterns>
      <comment>defined variable</comment>
      <match>(\$[^\s\=]+)</match>
      <name>variable.other.constant.sfz</name>
    </patterns>
  </sfz2_directives>
  <sfz2_sound-source>
    <patterns>
      <comment>opcodes: (default_path): any string</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(default_path)(=?)</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.$1.sfz</name>
        </1>
        <2>
          <name>keyword.operator.assignment.sfz</name>
        </2>
      </beginCaptures>
      <end>(?=(\s//|$))</end>
      <contentName>string.unquoted.sfz</contentName>
    </patterns>
    <patterns>
      <comment>opcodes: (direction): (forward|reverse)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(direction)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.sample-playback.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_forward-reverse</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loop_count): (0 to 4294967296 loops)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(loop_count)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.sample-playback.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loop_type): (forward|backward|alternate)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(loop_type)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.sample-playback.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_forward-backward-alternate</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (md5): (128-bit hex md5 hash)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(md5)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.sound-source.sample-playback.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_md5</include>
      </patterns>
    </patterns>
  </sfz2_sound-source>
  <sfz2_instrument-settings>
    <patterns>
      <comment>opcodes: (octave_offset): (-10 to 10 octaves)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(octave_offset)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg10-10</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (region_label|label_ccN): (any string)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(region_label|label_cc(?:\d{1,3})?)(=?)</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
        <2>
          <name>keyword.operator.assignment.sfz</name>
        </2>
      </beginCaptures>
      <end>(?=(\s//|$))</end>
      <contentName>string.unquoted.sfz</contentName>
    </patterns>
    <patterns>
      <comment>opcodes: (set_ccN): (0 to 127 MIDI Controller)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(set_cc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (polyphony|note_polyphony): (0 to 127 voices)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(polyphony|note_polyphony)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.voice-lifecycle.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (note_selfmask|rt_dead): (on|off)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(note_selfmask|rt_dead)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.voice-lifecycle.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_on-off</include>
      </patterns>
    </patterns>
  </sfz2_instrument-settings>
  <sfz2_region-logic>
    <patterns>
      <comment>opcodes: (sustain_sw|sostenuto_sw): (on|off)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sustain_sw|sostenuto_sw)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_on-off</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (loprog|hiprog): (0 to 127 MIDI program)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(loprog|hiprog)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
  </sfz2_region-logic>
  <sfz2_performance-parameters>
    <patterns>
      <comment>opcodes: (volume_onccN): (-144 to 6 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(volume_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg144-6</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (phase): (normal|invert)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(phase)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_normal-invert</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (width_onccN): (-100 to 100 percent)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(width_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg100-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (bend_smooth): (0 to 9600 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(bend_smooth)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (bend_stepup|bend_stepdown): (1 to 1200 cents)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(bend_stepup|bend_stepdown)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.pitch.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_1-1200</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (cutoff2|cutoff2_onccN): (0 to arbitrary Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(cutoff2|cutoff2_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (resonance_onccN|resonance2|resonance2_onccN): (0 to 40 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(resonance_oncc(?:\d{1,3})?|resonance2|resonance2_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-40</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (fil2_type): (lpf_1p|hpf_1p|lpf_2p|hpf_2p|bpf_2p|brf_2p)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(fil2_type)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.filters.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_lpf-hpf-bpf-brf</include>
      </patterns>
    </patterns>
  </sfz2_performance-parameters>
  <sfz2_modulation>
    <patterns>
      <comment>opcodes: (egN_(curve|loop|points|sustain)): (positive int)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eg\d{2}_(curve|loop|points|sustain))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (egN_level|egN_level_onccX): (-1 to 1 float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((eg\d{2}_level\d*)(_oncc(?:\d{1,3})?)?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg1-1</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (egN_shapeX): (-10 to 10 number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eg\d{2}_shape\d+)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg10-10</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (egN_time|egN_time_onccX): (0 to 100 seconds)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((eg\d{2}_time\d*)(_oncc(?:\d{1,3})?)?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_wave|lfoN_count|lfoN_freq|lfoN_freq_onccX|lfoN_freq_smoothccX): (positive int)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_(wave|count|freq_(smooth|step)cc(?:\d{1,3})?))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_freq|lfoN_freq_onccN): (-20 to 20 Hz)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_freq(_oncc(?:\d{1,3})?)?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg20-20</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_delay|lfoN_delay_onccX|lfoN_fade|lfoN_fade_onccX): (0 to 100 seconds)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_(delay|fade)(_oncc(?:\d{1,3})?)?|count)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_phase|lfoN_phase_onccX): (0 to 1 number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_phase(_oncc(?:\d{1,3})?)?|count)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-1</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (other eg destinations): (any float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(eg\d{2}_((depth_lfo|depthadd_lfo|freq_lfo)|((amplitude|depth|depth_lfo|depthadd_lfo|freq_lfo|pitch|cutoff2?|eq[1-3]freq|eq[1-3]bw|eq[1-3]gain|pan|resonance2?|volume|width)(_oncc(?:\d{1,3})?)?)))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (other lfo destinations): (any float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_((depth_lfo|depthadd_lfo|freq_lfo)|((amplitude|decim|bitred|depth_lfo|depthadd_lfo|freq_lfo|pitch|cutoff2?|eq[1-3]freq|eq[1-3]bw|eq[1-3]gain|pan|resonance2?|volume|width)(_oncc(?:\d{1,3})?)?)))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
  </sfz2_modulation>
  <sfz2_curves>
    <patterns>
      <comment>opcodes: (vN): (0 to 1 number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(v[0-9]{3})\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.curves.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-1</include>
      </patterns>
    </patterns>
  </sfz2_curves>
  <aria_instrument-settings>
    <patterns>
      <comment>opcodes: (hint_): (any number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(hint_[A-z_]*)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (set_hdccN|lohdccN|hihdccN): (any number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((?:(set_|lo|hi))hdcc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sustain_cc|sostenuto_cc|sustain_lo|sostenuto_lo): (0 to 127 MIDI byte)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sustain_cc|sostenuto_cc|sustain_lo|sostenuto_lo)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sw_octave_offset): (-10 to 10 octaves)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sw_octave_offset)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_neg10-10</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (off_curve): (0 to any curve)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(off_curve)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.voice-lifecycle.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (off_shape|off_time): (-10 to 10 number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(off_shape|off_time)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.instrument-settings.voice-lifecycle.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg10-10</include>
      </patterns>
    </patterns>
  </aria_instrument-settings>
  <aria_region-logic>
    <patterns>
      <comment>opcodes: (sw_default|sw_lolast|sw_hilast): (0 to 127 MIDI Note)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sw_default|sw_lolast|sw_hilast)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (sw_label): (any string)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(sw_label)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_any_continuous</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (varNN_curveccX): (0 to any curve)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(var\d{2}_curvecc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (varNN_mod): (add|mult)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(var\d{2}_mod)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_add-mult</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (varNN_onccX|varNN_target): (any float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b((var\d{2}_oncc(?:\d{1,3})?)|(var\d{2}_(pitch|cutoff|resonance|cutoff2|resonance2|eq[1-3]freq|eq[1-3]bw|eq[1-3]gain|volume|amplitude|pan|width)))\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.region-logic.midi-conditions.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
  </aria_region-logic>
  <aria_performance-parameters>
    <patterns>
      <comment>opcodes: (amplitude|amplitude_onccN|global_amplitude|master_amplitude|group_amplitude): (0 to 100 percent)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amplitude|amplitude_oncc(?:\d{1,3})?|global_amplitude|master_amplitude|group_amplitude)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_0-100</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplitude_curveccN): (any positive curve)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amplitude_curvecc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (amplitude_smoothccN): (0 to 9600 number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(amplitude_smoothcc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-9600</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (pan_law): (balance|mma)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(pan_law)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifier.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_balance-mma</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (global_volume|master_volume|group_volume|volume_onccN): (-144 to 6 dB)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(global_volume|master_volume|group_volume|volume_oncc(?:\d{1,3})?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.performance-parameters.amplifiers.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg144-6</include>
      </patterns>
    </patterns>
  </aria_performance-parameters>
  <aria_modulation>
    <patterns>
      <comment>opcodes: (ampeg_attack_shape|ampeg_decay_shape|ampeg_release_shape|egN_shapeX): (-10 to 10 float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(ampeg_attack_shape|ampeg_decay_shape|ampeg_release_shape|eg\d{2}_shape\d+)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_neg10-10</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (ampeg_release_zero|ampeg_decay_zero): (true|false)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(ampeg_release_zero|ampeg_decay_zero)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.envelope-generators.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_on-off</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_offset|lfoN_offset2|lfoN_ratio|lfoN_ratio2|lfoN_scale|lfoN_scale2): (any float)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_(offset|ratio|scale)2?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#float_any</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (lfoN_wave|lfoN_wav2): (0 to 127 MIDI Number)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(lfo\d{2}_wave2?)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.modulation.lfo.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_0-127</include>
      </patterns>
    </patterns>
  </aria_modulation>
  <aria_curves>
    <patterns>
      <comment>opcodes: (curve_index): (any positive integer)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(curve_index)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.curves.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_positive</include>
      </patterns>
    </patterns>
  </aria_curves>
  <aria_effects>
    <patterns>
      <comment>opcodes: (param_offset): (any integer)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(param_offset)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.effects.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#int_any</include>
      </patterns>
    </patterns>
    <patterns>
      <comment>opcodes: (vendor_specific): (any to continuous string)</comment>
      <name>meta.opcode.sfz</name>
      <begin>\b(vendor_specific)\b</begin>
      <beginCaptures>
        <1>
          <name>variable.language.effects.$1.sfz</name>
        </1>
      </beginCaptures>
      <end>\s|$</end>
      <patterns>
        <include>#string_any_continuous</include>
      </patterns>
    </patterns>
  </aria_effects>
  <float_neg30000-30000>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)\b(30000|([0-9]|[1-9][0-9]{1,3}|2[0-9]{4})(\.\d*)?)\b)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)\b(30000|([0-9]|[1-9][0-9]{1,3}|2[0-9]{4})(\.\d*)?)\b)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg30000-30000>
  <float_neg144-48>
    <patterns>
      <match>(=)(-(?&lt;!\.)(144|([1-9]|[1-8][0-9]|9[0-9]|1[0-4][0-3])(\.\d*)?)\b|\b(?&lt;!\.)(48|([0-9]|[1-3][0-9]|4[0-7])(\.\d*)?)\b)</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(-(?&lt;!\.)(144|([1-9]|[1-8][0-9]|9[0-9]|1[0-4][0-3])(\.\d*)?)\b|\b(?&lt;!\.)(48|([0-9]|[1-3][0-9]|4[0-7])(\.\d*)?)\b)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg144-48>
  <float_neg144-6>
    <patterns>
      <match>(=)(-(?&lt;!\.)(144|([1-9]|[1-8][0-9]|9[0-9]|1[0-4][0-3])(\.\d*)?)\b|\b(?&lt;!\.)(6|([0-5](\.\d*)?)\b))</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(-(?&lt;!\.)(144|([1-9]|[1-8][0-9]|9[0-9]|1[0-4][0-3])(\.\d*)?)\b|\b(?&lt;!\.)(6|([0-5](\.\d*)?)\b))).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg144-6>
  <float_neg200-200>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(200|([0-9]|[1-9][0-9]{1,2})(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(200|([0-9]|[1-9][0-9]{1,2})(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg200-200>
  <float_neg100-100>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(100|([0-9]|[1-9][0-9])(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(100|([0-9]|[1-9][0-9])(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg100-100>
  <float_neg96-12>
    <patterns>
      <match>(=)(-(?&lt;!\.)(96|([1-9]|[1-8][0-9]|9[0-5])(\.\d*)?)\b|\b(?&lt;!\.)(12|(([0-9]|1[01])(\.\d*)?)\b))</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(-(?&lt;!\.)(96|([1-9]|[1-8][0-9]|9[0-5])(\.\d*)?)\b|\b(?&lt;!\.)(12|(([0-9]|1[01])(\.\d*)?)\b))).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg96-12>
  <float_neg96-24>
    <patterns>
      <match>(=)(-(?&lt;!\.)(96|([1-9]|[1-8][0-9]|9[0-5])(\.\d*)?)\b|\b(?&lt;!\.)(24|(([0-9]|1[0-9]|2[0-3])(\.\d*)?)\b))</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(-(?&lt;!\.)(96|([1-9]|[1-8][0-9]|9[0-5])(\.\d*)?)\b|\b(?&lt;!\.)(24|(([0-9]|1[0-9]|2[0-3])(\.\d*)?)\b))).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg96-24>
  <float_neg20-20>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(20|(1?[0-9])(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(20|(1?[0-9])(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg20-20>
  <float_neg10-10>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(10|([0-9])(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(10|([0-9])(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg10-10>
  <float_neg4-4>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(4|([0-3])(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(4|([0-3])(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg4-4>
  <float_neg1-1>
    <patterns>
      <match>(=)((?:-?)(?&lt;!\.)(1|0(\.\d*)?))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)((?:-?)(?&lt;!\.)(1|0(\.\d*)?))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_neg1-1>
  <float_0-1>
    <patterns>
      <match>(=)(?&lt;!\.)(1|(0)(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(1|(0)(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-1>
  <float_0-4>
    <patterns>
      <match>(=)(?&lt;!\.)(4|([0-3])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(4|([0-3])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-4>
  <float_0-20>
    <patterns>
      <match>(=)(?&lt;!\.)(20|([0-9]|1[0-9])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(24|([0-9]|1[0-9])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-20>
  <float_0-24>
    <patterns>
      <match>(=)(?&lt;!\.)(24|([0-9]|1[0-9]|2[0-3])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(24|([0-9]|1[0-9]|2[0-3])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-24>
  <float_0-32>
    <patterns>
      <match>(=)(?&lt;!\.)(32|([0-9]|1[0-9]|2[0-9]|3[0-1])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(32|([0-9]|1[0-9]|2[0-9]|3[0-1])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-32>
  <float_0-40>
    <patterns>
      <match>(=)(?&lt;!\.)(40|([0-9]|[1-3][0-9])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(40|([0-9]|[1-3][0-9])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-40>
  <float_0-100>
    <patterns>
      <match>(=)(?&lt;!\.)(100|([0-9]|[1-9][0-9])(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(100|([0-9]|[1-9][0-9])(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-100>
  <float_0-200>
    <patterns>
      <match>(=)(?&lt;!\.)(200|([0-9]|[1-9][0-9]|1[0-9]{2})(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(200|([0-9]|[1-9][0-9]|1[0-9]{2})(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-200>
  <float_0-500>
    <patterns>
      <match>(=)(?&lt;!\.)(500|([0-9]|[1-8][0-9]|9[0-9]|[1-4][0-9]{2})(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)(500|([0-9]|[1-8][0-9]|9[0-9]|[1-4][0-9]{2})(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-500>
  <float_0-30000>
    <patterns>
      <match>(=)(?&lt;!\.)\b(30000|([0-9]|[1-9][0-9]{1,3}|2[0-9]{4})(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(?&lt;!\.)\b(30000|([0-9]|[1-9][0-9]{1,3}|2[0-9]{4})(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_0-30000>
  <float_positive>
    <patterns>
      <match>(=)(\d+(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(\d+(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_positive>
  <float_any>
    <patterns>
      <match>(=)(-?\b\d+(\.\d*)?)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.float.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b\d+(\.\d*)?)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </float_any>
  <int_neg12000-12000>
    <patterns>
      <match>(=)(-?\b(12000|[0-9]|[1-9][0-9]{1,3}|1[01][0-9]{3}))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b(12000|[0-9]|[1-9][0-9]{1,3}|1[01][0-9]{3}))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg12000-12000>
  <int_neg9600-9600>
    <patterns>
      <match>(=)(-?([0-9]|[1-9][0-9]{1,2}|[1-8][0-9]{3}|9[0-5][0-9]{2}|9600))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?([0-9]|[1-9][0-9]{1,2}|[1-8][0-9]{3}|9[0-5][0-9]{2}|9600))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg9600-9600>
  <int_neg8192-8192>
    <patterns>
      <match>(=)(-?([0-9]|[1-9][0-9]|[1-9][0-9]{2}|[1-7][0-9]{3}|80[0-9]{2}|81[0-8][0-9]|819[0-2]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?([0-9]|[1-9][0-9]|[1-9][0-9]{2}|[1-7][0-9]{3}|80[0-9]{2}|81[0-8][0-9]|819[0-2]))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg8192-8192>
  <int_neg1200-1200>
    <patterns>
      <match>(=)(-?\b(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9]{2}))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9]{2}))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg1200-1200>
  <int_neg100-100>
    <patterns>
      <match>(=)(-?\b(100|[0-9]|[1-9][0-9]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b(100|[0-9]|[1-9][0-9]))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg100-100>
  <int_neg10-10>
    <patterns>
      <match>(=)(-?\b(10|[0-9]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b(10|[0-9]))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg10-10>
  <int_neg1-127>
    <patterns>
      <match>(=)(-1|[0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-1|[0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg1-127>
  <int_neg127-127>
    <patterns>
      <match>(=)(-?\b([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(-?\b([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7]))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_neg127-127>
  <int_0-127>
    <patterns>
      <match>(=)([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_0-127>
  <int_0-127_or_string_note>
    <patterns>
      <match>(=)(([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])|[cdefgabCDEFGAB]\#?(-1|[0-9]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-7])|[cdefgabCDEFGAB]\#?(-1|[0-9]))\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_0-127_or_string_note>
  <int_0-1024>
    <patterns>
      <match>(=)([0-9]|[1-9][0-9]|[1-9][0-9]{2}|10[01][0-9]|102[0-4])\b</match>
      <name>constant.numeric.integer.sfz</name>
    </patterns>
    <patterns>
      <match>(?!(=)([0-9]|[1-9][0-9]|[1-9][0-9]{2}|10[01][0-9]|102[0-4])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_0-1024>
  <int_0-1200>
    <patterns>
      <match>(=)(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9{2}])\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9]{2}])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_0-1200>
  <int_0-9600>
    <patterns>
      <match>(=)([0-9]|[1-9][0-9]{1,2}|[1-8][0-9]{3}|9[0-5][0-9]{2}|9600)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!(=)([0-9]|[1-9][0-9]{1,2}|[1-8][0-9]{3}|9[0-5][0-9]{2}|9600)\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_0-9600>
  <int_1-16>
    <patterns>
      <match>(=)([1-9]|1[0-6])\b</match>
      <name>constant.numeric.integer.sfz</name>
    </patterns>
    <patterns>
      <match>(?!(=)([1-9]|1[0-6])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_1-16>
  <int_1-100>
    <patterns>
      <match>(=)(100|[1-9]|[1-9][0-9])\b</match>
      <name>constant.numeric.integer.sfz</name>
    </patterns>
    <patterns>
      <match>(?!(=)(100|[1-9]|[1-9][0-9])\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_1-100>
  <int_1-1200>
    <patterns>
      <match>(=)(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9]{2})\b</match>
      <name>constant.numeric.integer.sfz</name>
    </patterns>
    <patterns>
      <match>(?!(=)(1200|[0-9]|[1-9][0-9]{1,2}|1[01][0-9]{2})\b)[^\s]*</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_1-1200>
  <int_positive>
    <patterns>
      <match>(=)(\d+)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>((?!(\d+)).)*$</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_positive>
  <int_positive_or_neg1>
    <patterns>
      <match>(=)(-1|\d+)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>((?!(-1|\d+)\b).)*$</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_positive_or_neg1>
  <int_any>
    <patterns>
      <match>(=)(-?\b\d+)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>constant.numeric.integer.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>((?!(-?\b\d+)).)*$</match>
      <name>invalid.sfz</name>
    </patterns>
  </int_any>
  <string_add-mult>
    <patterns>
      <match>(=)(add|mult)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(add|mult)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_add-mult>
  <string_attack-release-first-legato>
    <patterns>
      <match>(=)(attack|release|first|legato)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(attack|release|first|legato)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_attack-release-first-legato>
  <string_balance-mma>
    <patterns>
      <match>(=)(balance|mma)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(balance|mma)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_balance-mma>
  <string_current-previous>
    <patterns>
      <match>(=)(current|previous)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(current|previous)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_current-previous>
  <string_fast-normal-time>
    <patterns>
      <match>(=)(fast|normal|time)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(fast|normal|time)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_fast-normal-time>
  <string_forward-backward-alternate>
    <patterns>
      <match>(=)(forward|backward|alternate)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(forward|backward|alternate)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_forward-backward-alternate>
  <string_forward-reverse>
    <patterns>
      <match>(=)(forward|reverse)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(forward|reverse)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_forward-reverse>
  <string_gain-power>
    <patterns>
      <match>(=)(gain|power)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(gain|power)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_gain-power>
  <string_loop_mode>
    <patterns>
      <match>(=)(no_loop|one_shot|loop_continuous|loop_sustain)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(no_loop|one_shot|loop_continuous|loop_sustain)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_loop_mode>
  <string_lpf-hpf-bpf-brf>
    <patterns>
      <match>(=)(lpf_1p|hpf_1p|lpf_2p|hpf_2p|bpf_2p|brf_2p)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(lpf_1p|hpf_1p|lpf_2p|hpf_2p|bpf_2p|brf_2p)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_lpf-hpf-bpf-brf>
  <string_md5>
    <patterns>
      <match>(=)([abcdef0-9]{32})\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=([abcdef0-9]{32})).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_md5>
  <string_normal-invert>
    <patterns>
      <match>(=)(normal|invert)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(normal|invert)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_normal-invert>
  <string_on-off>
    <patterns>
      <match>(=)(true|false|on|off|0|1)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.unquoted.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=(true|false|on|off|0|1)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_on-off>
  <string_note>
    <patterns>
      <match>(=)([cdefgabCDEFGAB]\#?(-1|[0-9]))\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.note.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=([cdefgabCDEFGAB]\#?(-1|[0-9]))).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_note>
  <string_any_continuous>
    <patterns>
      <match>(=)([^\s]+)\b</match>
      <captures>
        <1>
          <name>keyword.operator.assignment.sfz</name>
        </1>
        <2>
          <name>string.note.sfz</name>
        </2>
      </captures>
    </patterns>
    <patterns>
      <match>(?!=([^\s]+)).*</match>
      <name>invalid.sfz</name>
    </patterns>
  </string_any_continuous>
</repository>
<scopeName>source.sfz</scopeName>